
const incidencias = [
  {
    id: 1,
    codigo: "INC-2026-000001",
    jira_id: "GFT-1",
    titulo: "No puedo iniciar sesion en el portal",
    descripcion: "El usuario intenta acceder al portal corporativo y recibe error 403.",
    estado: "Cerrada",
    prioridad: "Alta",
    categoria: "Accesos",
    reportado_por: "Laura Gomez",
    asignado_a: "Carlos Ruiz",
    equipo: "Soporte N1",
    origen: "Web",
    causa: "Token de sesion expirado sin renovacion automatica",
    solucion: "Se reseteo el token y se actualizo la configuracion de expiracion",
    fecha_creacion: "2026-05-01T08:00:00",
    fecha_actualizacion: "2026-05-01T10:30:00",
    fecha_cierre: "2026-05-01T10:30:00",
    sla_vencimiento: "2026-05-02T08:00:00"
  },
  {
    id: 2,
    codigo: "INC-2026-000002",
    jira_id: "GFT-2",
    titulo: "Pantalla azul en equipo de contabilidad",
    descripcion: "El ordenador de Maria Torres muestra BSOD al arrancar. Codigo de error: 0x0000007E.",
    estado: "Resuelta",
    prioridad: "Alta",
    categoria: "Hardware",
    reportado_por: "Maria Torres",
    asignado_a: "Jorge Perez",
    equipo: "Soporte N2",
    origen: "Telefono",
    causa: "Driver de tarjeta grafica corrupto tras actualizacion de Windows",
    solucion: "Se reinstalo el driver en version estable anterior",
    fecha_creacion: "2026-05-02T09:15:00",
    fecha_actualizacion: "2026-05-02T14:00:00",
    fecha_cierre: "2026-05-02T14:00:00",
    sla_vencimiento: "2026-05-03T09:15:00"
  },
  {
    id: 3,
    codigo: "INC-2026-000003",
    jira_id: null,
    titulo: "El servidor de correo no responde",
    descripcion: "Los usuarios de la sede de Madrid no pueden enviar ni recibir emails desde las 08:00.",
    estado: "Cerrada",
    prioridad: "Critica",
    categoria: "Red",
    reportado_por: "Admin Sistema",
    asignado_a: "Sofia Herrera",
    equipo: "Infraestructura",
    origen: "Email",
    causa: "El servicio SMTP cayo por falta de espacio en disco",
    solucion: "Se libero espacio y se reinicio el servicio",
    fecha_creacion: "2026-05-03T08:05:00",
    fecha_actualizacion: "2026-05-03T09:00:00",
    fecha_cierre: "2026-05-03T09:00:00",
    sla_vencimiento: "2026-05-03T12:05:00"
  },
  {
    id: 4,
    codigo: "INC-2026-000004",
    jira_id: "GFT-4",
    titulo: "No se puede acceder a la carpeta compartida de proyectos",
    descripcion: "El equipo de desarrollo no ve la carpeta \\\\servidor\\proyectos desde ayer por la tarde.",
    estado: "Resuelta",
    prioridad: "Media",
    categoria: "Accesos",
    reportado_por: "Pedro Sanchez",
    asignado_a: "Carlos Ruiz",
    equipo: "Soporte N1",
    origen: "Web",
    causa: "Los permisos del directorio fueron sobrescritos por un script de mantenimiento",
    solucion: "Se restauraron los permisos desde la copia de seguridad de politicas",
    fecha_creacion: "2026-05-04T10:00:00",
    fecha_actualizacion: "2026-05-04T13:45:00",
    fecha_cierre: "2026-05-04T13:45:00",
    sla_vencimiento: "2026-05-06T10:00:00"
  },
  {
    id: 5,
    codigo: "INC-2026-000005",
    jira_id: "GFT-5",
    titulo: "La aplicacion de nominas se cierra sola",
    descripcion: "Al generar el informe mensual, la aplicacion SAGE cierra de forma inesperada sin mensaje de error.",
    estado: "En progreso",
    prioridad: "Alta",
    categoria: "Software",
    reportado_por: "Rosa Blanco",
    asignado_a: "Ana Martinez",
    equipo: "Soporte N2",
    origen: "Telefono",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-05T11:30:00",
    fecha_actualizacion: "2026-05-05T15:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-06T11:30:00"
  },
  {
    id: 6,
    codigo: "INC-2026-000006",
    jira_id: null,
    titulo: "Impresora de planta 3 sin conexion",
    descripcion: "La impresora HP LaserJet del tercer piso no aparece en la red desde el viernes.",
    estado: "Asignada",
    prioridad: "Baja",
    categoria: "Hardware",
    reportado_por: "Luis Fernandez",
    asignado_a: "Jorge Perez",
    equipo: "Soporte N1",
    origen: "Email",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-06T09:00:00",
    fecha_actualizacion: "2026-05-06T09:30:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-09T09:00:00"
  },
  {
    id: 7,
    codigo: "INC-2026-000007",
    jira_id: "GFT-7",
    titulo: "VPN no conecta desde fuera de la oficina",
    descripcion: "Varios empleados en teletrabajo reportan que la VPN corporativa da timeout al intentar conectar.",
    estado: "Cerrada",
    prioridad: "Critica",
    categoria: "Red",
    reportado_por: "Marta Lopez",
    asignado_a: "Sofia Herrera",
    equipo: "Infraestructura",
    origen: "Email",
    causa: "El certificado SSL de la VPN habia expirado",
    solucion: "Se renovo el certificado y se reinicio el servidor VPN",
    fecha_creacion: "2026-05-07T07:45:00",
    fecha_actualizacion: "2026-05-07T09:00:00",
    fecha_cierre: "2026-05-07T09:00:00",
    sla_vencimiento: "2026-05-07T11:45:00"
  },
  {
    id: 8,
    codigo: "INC-2026-000008",
    jira_id: null,
    titulo: "Usuario bloqueado tras intentos fallidos",
    descripcion: "El usuario jdoe@empresa.com esta bloqueado. Dice que no cambio su contrasena.",
    estado: "Resuelta",
    prioridad: "Media",
    categoria: "Accesos",
    reportado_por: "John Doe",
    asignado_a: "Carlos Ruiz",
    equipo: "Soporte N1",
    origen: "Telefono",
    causa: "Un proceso automatico estaba intentando autenticarse con credenciales antiguas",
    solucion: "Se desbloqueo el usuario y se actualizo el proceso con las nuevas credenciales",
    fecha_creacion: "2026-05-08T10:20:00",
    fecha_actualizacion: "2026-05-08T11:00:00",
    fecha_cierre: "2026-05-08T11:00:00",
    sla_vencimiento: "2026-05-10T10:20:00"
  },
  {
    id: 9,
    codigo: "INC-2026-000009",
    jira_id: "GFT-9",
    titulo: "Lentitud extrema en el sistema ERP",
    descripcion: "El modulo de compras del ERP tarda mas de 5 minutos en cargar. Antes era instantaneo.",
    estado: "En progreso",
    prioridad: "Alta",
    categoria: "Software",
    reportado_por: "Elena Castro",
    asignado_a: "Ana Martinez",
    equipo: "Soporte N2",
    origen: "Web",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-09T08:30:00",
    fecha_actualizacion: "2026-05-09T12:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-10T08:30:00"
  },
  {
    id: 10,
    codigo: "INC-2026-000010",
    jira_id: null,
    titulo: "Monitor sin imagen al encender el equipo",
    descripcion: "El monitor del puesto 4B no muestra imagen aunque el PC enciende correctamente.",
    estado: "Resuelta",
    prioridad: "Media",
    categoria: "Hardware",
    reportado_por: "Tomas Rivera",
    asignado_a: "Jorge Perez",
    equipo: "Soporte N1",
    origen: "Email",
    causa: "Cable DisplayPort danado internamente",
    solucion: "Se sustituyo el cable por uno nuevo del almacen",
    fecha_creacion: "2026-05-10T09:00:00",
    fecha_actualizacion: "2026-05-10T10:30:00",
    fecha_cierre: "2026-05-10T10:30:00",
    sla_vencimiento: "2026-05-12T09:00:00"
  },
  {
    id: 11,
    codigo: "INC-2026-000011",
    jira_id: "GFT-11",
    titulo: "No llegan notificaciones push de la app movil",
    descripcion: "Los tecnicos no reciben alertas en el movil cuando se les asigna una incidencia.",
    estado: "Nueva",
    prioridad: "Media",
    categoria: "Software",
    reportado_por: "Admin Sistema",
    asignado_a: null,
    equipo: null,
    origen: "Web",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-11T11:00:00",
    fecha_actualizacion: "2026-05-11T11:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-13T11:00:00"
  },
  {
    id: 12,
    codigo: "INC-2026-000012",
    jira_id: null,
    titulo: "Fallo en la copia de seguridad nocturna",
    descripcion: "El backup de las 02:00 ha fallado tres noches seguidas. El log dice 'Disk quota exceeded'.",
    estado: "En progreso",
    prioridad: "Critica",
    categoria: "Software",
    reportado_por: "Admin Sistema",
    asignado_a: "Sofia Herrera",
    equipo: "Infraestructura",
    origen: "Email",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-12T06:00:00",
    fecha_actualizacion: "2026-05-12T08:30:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-12T10:00:00"
  },
  {
    id: 13,
    codigo: "INC-2026-000013",
    jira_id: "GFT-13",
    titulo: "El escaner no funciona con el nuevo controlador",
    descripcion: "Tras actualizar Windows, el escaner Canon del departamento legal dejo de ser detectado.",
    estado: "Pendiente",
    prioridad: "Baja",
    categoria: "Hardware",
    reportado_por: "Isabel Mora",
    asignado_a: "Jorge Perez",
    equipo: "Soporte N1",
    origen: "Email",
    causa: "El fabricante aun no ha publicado controlador compatible con la nueva version de Windows",
    solucion: null,
    fecha_creacion: "2026-05-12T10:00:00",
    fecha_actualizacion: "2026-05-13T09:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-15T10:00:00"
  },
  {
    id: 14,
    codigo: "INC-2026-000014",
    jira_id: null,
    titulo: "Pantalla de login en bucle tras cambio de contrasena",
    descripcion: "Al cambiar la contrasena, el sistema redirige a login de nuevo sin dejar entrar.",
    estado: "Resuelta",
    prioridad: "Alta",
    categoria: "Accesos",
    reportado_por: "Carmen Vega",
    asignado_a: "Carlos Ruiz",
    equipo: "Soporte N1",
    origen: "Telefono",
    causa: "La cookie de sesion antigua bloqueaba la nueva autenticacion",
    solucion: "Se borraron las cookies de sesion en servidor y se pidio al usuario limpiar el navegador",
    fecha_creacion: "2026-05-13T08:00:00",
    fecha_actualizacion: "2026-05-13T09:15:00",
    fecha_cierre: "2026-05-13T09:15:00",
    sla_vencimiento: "2026-05-14T08:00:00"
  },
  {
    id: 15,
    codigo: "INC-2026-000015",
    jira_id: "GFT-15",
    titulo: "Caida de la red en la sala de reuniones B",
    descripcion: "Los equipos de la sala B no tienen acceso a internet ni a recursos internos.",
    estado: "Cerrada",
    prioridad: "Alta",
    categoria: "Red",
    reportado_por: "Director Operaciones",
    asignado_a: "Sofia Herrera",
    equipo: "Infraestructura",
    origen: "Telefono",
    causa: "Switch de la sala en estado frozen por fallo de firmware",
    solucion: "Se reinicio el switch y se actualizo el firmware",
    fecha_creacion: "2026-05-13T12:00:00",
    fecha_actualizacion: "2026-05-13T13:30:00",
    fecha_cierre: "2026-05-13T13:30:00",
    sla_vencimiento: "2026-05-14T12:00:00"
  },
  {
    id: 16,
    codigo: "INC-2026-000016",
    jira_id: null,
    titulo: "No se puede abrir el fichero Excel del dashboard",
    descripcion: "El archivo Dashboard_Ventas_Q2.xlsx da error de contenido no valido al abrirlo.",
    estado: "Resuelta",
    prioridad: "Media",
    categoria: "Software",
    reportado_por: "Felix Ortega",
    asignado_a: "Ana Martinez",
    equipo: "Soporte N2",
    origen: "Email",
    causa: "El archivo fue corrompido durante una transferencia por red inestable",
    solucion: "Se restauro el archivo desde la copia de seguridad del dia anterior",
    fecha_creacion: "2026-05-14T09:30:00",
    fecha_actualizacion: "2026-05-14T11:00:00",
    fecha_cierre: "2026-05-14T11:00:00",
    sla_vencimiento: "2026-05-16T09:30:00"
  },
  {
    id: 17,
    codigo: "INC-2026-000017",
    jira_id: "GFT-17",
    titulo: "Solicitud de nuevo acceso al sistema de RRHH",
    descripcion: "La empleada nueva Lucia Pardo necesita acceso al modulo de vacaciones de SAP.",
    estado: "Asignada",
    prioridad: "Baja",
    categoria: "Accesos",
    reportado_por: "Departamento RRHH",
    asignado_a: "Carlos Ruiz",
    equipo: "Soporte N1",
    origen: "Web",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-14T10:00:00",
    fecha_actualizacion: "2026-05-14T10:15:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-17T10:00:00"
  },
  {
    id: 18,
    codigo: "INC-2026-000018",
    jira_id: null,
    titulo: "El sistema de fichajes no registra salidas",
    descripcion: "El reloj de control de presencia registra entradas pero no las salidas desde el lunes.",
    estado: "En progreso",
    prioridad: "Alta",
    categoria: "Hardware",
    reportado_por: "Responsable RRHH",
    asignado_a: "Jorge Perez",
    equipo: "Soporte N2",
    origen: "Telefono",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-15T08:00:00",
    fecha_actualizacion: "2026-05-15T10:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-16T08:00:00"
  },
  {
    id: 19,
    codigo: "INC-2026-000019",
    jira_id: "GFT-19",
    titulo: "Error 500 en la API de clientes",
    descripcion: "El endpoint /api/clientes devuelve 500 de forma intermitente. Afecta a la app movil.",
    estado: "En progreso",
    prioridad: "Critica",
    categoria: "Software",
    reportado_por: "Admin Sistema",
    asignado_a: "Ana Martinez",
    equipo: "Soporte N2",
    origen: "Web",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-15T11:00:00",
    fecha_actualizacion: "2026-05-15T13:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-15T15:00:00"
  },
  {
    id: 20,
    codigo: "INC-2026-000020",
    jira_id: null,
    titulo: "Teclado con teclas pegadas en puesto de atencion al cliente",
    descripcion: "El teclado del puesto 2A tiene varias teclas que no responden correctamente.",
    estado: "Cerrada",
    prioridad: "Baja",
    categoria: "Hardware",
    reportado_por: "Sandra Jimenez",
    asignado_a: "Jorge Perez",
    equipo: "Soporte N1",
    origen: "Email",
    causa: "Derrame de liquido sobre el teclado",
    solucion: "Se sustituyo el teclado por uno nuevo del almacen",
    fecha_creacion: "2026-05-15T12:00:00",
    fecha_actualizacion: "2026-05-15T14:00:00",
    fecha_cierre: "2026-05-15T14:00:00",
    sla_vencimiento: "2026-05-18T12:00:00"
  },
  {
    id: 21,
    codigo: "INC-2026-000021",
    jira_id: "GFT-21",
    titulo: "No se puede acceder al correo desde Outlook",
    descripcion: "Outlook muestra el error 'No se puede conectar con el servidor' en varios equipos de ventas.",
    estado: "Resuelta",
    prioridad: "Alta",
    categoria: "Software",
    reportado_por: "Equipo Ventas",
    asignado_a: "Ana Martinez",
    equipo: "Soporte N2",
    origen: "Telefono",
    causa: "La contrasena de la cuenta de servicio de Exchange habia expirado",
    solucion: "Se renuevo la contrasena y se reinicio el servicio de Exchange",
    fecha_creacion: "2026-05-16T08:30:00",
    fecha_actualizacion: "2026-05-16T10:00:00",
    fecha_cierre: "2026-05-16T10:00:00",
    sla_vencimiento: "2026-05-17T08:30:00"
  },
  {
    id: 22,
    codigo: "INC-2026-000022",
    jira_id: null,
    titulo: "Caida del servidor de base de datos en produccion",
    descripcion: "El servidor PostgreSQL de produccion no responde. Todas las aplicaciones estan caidas.",
    estado: "Cerrada",
    prioridad: "Critica",
    categoria: "Software",
    reportado_por: "Admin Sistema",
    asignado_a: "Sofia Herrera",
    equipo: "Infraestructura",
    origen: "Email",
    causa: "El servidor se quedo sin memoria RAM por una consulta sin limite que bloqueo todos los procesos",
    solucion: "Se mato el proceso problematico, se reinicio el servidor y se aplico limite de memoria por consulta",
    fecha_creacion: "2026-05-16T02:00:00",
    fecha_actualizacion: "2026-05-16T04:30:00",
    fecha_cierre: "2026-05-16T04:30:00",
    sla_vencimiento: "2026-05-16T06:00:00"
  },
  {
    id: 23,
    codigo: "INC-2026-000023",
    jira_id: "GFT-23",
    titulo: "Los informes PDF no se generan correctamente",
    descripcion: "Al exportar cualquier informe a PDF desde el BI, el archivo sale en blanco.",
    estado: "Pendiente",
    prioridad: "Media",
    categoria: "Software",
    reportado_por: "Direccion",
    asignado_a: "Ana Martinez",
    equipo: "Soporte N2",
    origen: "Web",
    causa: "Fallo en la libreria de renderizado PDF tras una actualizacion automatica",
    solucion: null,
    fecha_creacion: "2026-05-16T10:00:00",
    fecha_actualizacion: "2026-05-17T09:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-18T10:00:00"
  },
  {
    id: 24,
    codigo: "INC-2026-000024",
    jira_id: null,
    titulo: "Acceso denegado al repositorio de codigo",
    descripcion: "El desarrollador nuevo Pablo Gil no puede hacer clone del repositorio en GitLab.",
    estado: "Resuelta",
    prioridad: "Media",
    categoria: "Accesos",
    reportado_por: "Pablo Gil",
    asignado_a: "Carlos Ruiz",
    equipo: "Soporte N1",
    origen: "Email",
    causa: "No se habia anadido al grupo de desarrollo en GitLab",
    solucion: "Se anadio el usuario al grupo con permisos de Developer",
    fecha_creacion: "2026-05-17T09:00:00",
    fecha_actualizacion: "2026-05-17T09:45:00",
    fecha_cierre: "2026-05-17T09:45:00",
    sla_vencimiento: "2026-05-19T09:00:00"
  },
  {
    id: 25,
    codigo: "INC-2026-000025",
    jira_id: "GFT-25",
    titulo: "Wifi muy lenta en la zona de la cafeteria",
    descripcion: "Los empleados que trabajan desde la cafeteria reportan velocidad inferior a 1Mbps.",
    estado: "En progreso",
    prioridad: "Baja",
    categoria: "Red",
    reportado_por: "Varios empleados",
    asignado_a: "Sofia Herrera",
    equipo: "Infraestructura",
    origen: "Web",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-17T11:00:00",
    fecha_actualizacion: "2026-05-18T08:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-20T11:00:00"
  },
  {
    id: 26,
    codigo: "INC-2026-000026",
    jira_id: null,
    titulo: "El antivirus bloquea el instalador de la aplicacion de contabilidad",
    descripcion: "Windows Defender marca como amenaza el instalador de ContaPlus v14 e impide su ejecucion.",
    estado: "Resuelta",
    prioridad: "Media",
    categoria: "Software",
    reportado_por: "Rosa Blanco",
    asignado_a: "Ana Martinez",
    equipo: "Soporte N2",
    origen: "Telefono",
    causa: "Falso positivo del antivirus con el instalador firmado del proveedor",
    solucion: "Se anadio la excepcion al antivirus y se completo la instalacion",
    fecha_creacion: "2026-05-17T12:00:00",
    fecha_actualizacion: "2026-05-17T13:30:00",
    fecha_cierre: "2026-05-17T13:30:00",
    sla_vencimiento: "2026-05-19T12:00:00"
  },
  {
    id: 27,
    codigo: "INC-2026-000027",
    jira_id: "GFT-27",
    titulo: "Fallo en la sincronizacion con Jira",
    descripcion: "Las incidencias creadas en el portal no se sincronizan con Jira desde las 10:00.",
    estado: "Nueva",
    prioridad: "Alta",
    categoria: "Software",
    reportado_por: "Admin Sistema",
    asignado_a: null,
    equipo: null,
    origen: "Web",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-18T10:00:00",
    fecha_actualizacion: "2026-05-18T10:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-19T10:00:00"
  },
  {
    id: 28,
    codigo: "INC-2026-000028",
    jira_id: null,
    titulo: "Solicitud de reinstalacion de Windows en portatil",
    descripcion: "El portatil de Jorge Medina va muy lento y el usuario pide formateo y reinstalacion.",
    estado: "Asignada",
    prioridad: "Baja",
    categoria: "Software",
    reportado_por: "Jorge Medina",
    asignado_a: "Jorge Perez",
    equipo: "Soporte N1",
    origen: "Email",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-18T11:00:00",
    fecha_actualizacion: "2026-05-18T11:30:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-21T11:00:00"
  },
  {
    id: 29,
    codigo: "INC-2026-000029",
    jira_id: "GFT-29",
    titulo: "La camara de videoconferencia no funciona en sala A",
    descripcion: "La camara Logitech de la sala de reuniones A no es detectada por Teams ni Zoom.",
    estado: "Resuelta",
    prioridad: "Media",
    categoria: "Hardware",
    reportado_por: "Secretaria Direccion",
    asignado_a: "Jorge Perez",
    equipo: "Soporte N1",
    origen: "Telefono",
    causa: "El hub USB al que estaba conectada la camara habia fallado",
    solucion: "Se conecto la camara directamente al puerto USB del equipo",
    fecha_creacion: "2026-05-18T14:00:00",
    fecha_actualizacion: "2026-05-18T15:00:00",
    fecha_cierre: "2026-05-18T15:00:00",
    sla_vencimiento: "2026-05-20T14:00:00"
  },
  {
    id: 30,
    codigo: "INC-2026-000030",
    jira_id: null,
    titulo: "Error al importar datos desde CSV en el ERP",
    descripcion: "Al importar el fichero de productos, el sistema devuelve 'Error de codificacion en linea 1'.",
    estado: "Resuelta",
    prioridad: "Media",
    categoria: "Software",
    reportado_por: "Almacen",
    asignado_a: "Ana Martinez",
    equipo: "Soporte N2",
    origen: "Email",
    causa: "El CSV estaba en codificacion ANSI en lugar de UTF-8",
    solucion: "Se convirtio el fichero a UTF-8 con Notepad++ y se reimporto correctamente",
    fecha_creacion: "2026-05-19T08:30:00",
    fecha_actualizacion: "2026-05-19T09:30:00",
    fecha_cierre: "2026-05-19T09:30:00",
    sla_vencimiento: "2026-05-21T08:30:00"
  },
  {
    id: 31,
    codigo: "INC-2026-000031",
    jira_id: "GFT-31",
    titulo: "Acceso a datos de otro departamento visible por error",
    descripcion: "Un usuario del departamento de marketing puede ver facturas del departamento financiero.",
    estado: "En progreso",
    prioridad: "Critica",
    categoria: "Accesos",
    reportado_por: "Responsable Seguridad",
    asignado_a: "Carlos Ruiz",
    equipo: "Soporte N2",
    origen: "Web",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-19T09:00:00",
    fecha_actualizacion: "2026-05-19T10:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-19T13:00:00"
  },
  {
    id: 32,
    codigo: "INC-2026-000032",
    jira_id: null,
    titulo: "El programa de diseno no abre archivos .AI",
    descripcion: "Adobe Illustrator 2025 da error al abrir ficheros creados con versiones anteriores.",
    estado: "Pendiente",
    prioridad: "Baja",
    categoria: "Software",
    reportado_por: "Equipo Diseno",
    asignado_a: "Ana Martinez",
    equipo: "Soporte N2",
    origen: "Email",
    causa: "Incompatibilidad conocida entre versiones de Illustrator",
    solucion: null,
    fecha_creacion: "2026-05-19T11:00:00",
    fecha_actualizacion: "2026-05-20T09:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-22T11:00:00"
  },
  {
    id: 33,
    codigo: "INC-2026-000033",
    jira_id: "GFT-33",
    titulo: "Perdida de paquetes en la conexion entre sedes",
    descripcion: "La conexion entre la sede de Madrid y Barcelona tiene perdida de paquetes del 40%.",
    estado: "En progreso",
    prioridad: "Critica",
    categoria: "Red",
    reportado_por: "Admin Sistema",
    asignado_a: "Sofia Herrera",
    equipo: "Infraestructura",
    origen: "Web",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-19T14:00:00",
    fecha_actualizacion: "2026-05-19T15:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-19T18:00:00"
  },
  {
    id: 34,
    codigo: "INC-2026-000034",
    jira_id: null,
    titulo: "No se puede firmar digitalmente en la plataforma de contratos",
    descripcion: "El certificado digital no es reconocido por la plataforma al intentar firmar un contrato.",
    estado: "Nueva",
    prioridad: "Alta",
    categoria: "Accesos",
    reportado_por: "Departamento Legal",
    asignado_a: null,
    equipo: null,
    origen: "Email",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-20T08:00:00",
    fecha_actualizacion: "2026-05-20T08:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-21T08:00:00"
  },
  {
    id: 35,
    codigo: "INC-2026-000035",
    jira_id: "GFT-35",
    titulo: "El dashboard de metricas no carga datos del ultimo mes",
    descripcion: "El panel de KPIs muestra datos correctos hasta abril pero mayo aparece en blanco.",
    estado: "En progreso",
    prioridad: "Alta",
    categoria: "Software",
    reportado_por: "Gerencia",
    asignado_a: "Ana Martinez",
    equipo: "Soporte N2",
    origen: "Web",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-20T09:00:00",
    fecha_actualizacion: "2026-05-20T11:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-21T09:00:00"
  },
  {
    id: 36,
    codigo: "INC-2026-000036",
    jira_id: null,
    titulo: "Microfono del portatil no funciona en videollamadas",
    descripcion: "El microfono integrado del portatil de Paula Ramos no captura audio en Teams.",
    estado: "Resuelta",
    prioridad: "Media",
    categoria: "Hardware",
    reportado_por: "Paula Ramos",
    asignado_a: "Jorge Perez",
    equipo: "Soporte N1",
    origen: "Telefono",
    causa: "La privacidad de Windows tenia bloqueado el acceso al microfono para Teams",
    solucion: "Se habilito el permiso de microfono para la aplicacion en la configuracion de privacidad",
    fecha_creacion: "2026-05-20T10:00:00",
    fecha_actualizacion: "2026-05-20T10:45:00",
    fecha_cierre: "2026-05-20T10:45:00",
    sla_vencimiento: "2026-05-22T10:00:00"
  },
  {
    id: 37,
    codigo: "INC-2026-000037",
    jira_id: "GFT-37",
    titulo: "Solicitud de aumento de cuota de almacenamiento en la nube",
    descripcion: "El equipo de diseno ha llenado su cuota de OneDrive y no puede subir mas archivos.",
    estado: "Asignada",
    prioridad: "Baja",
    categoria: "Accesos",
    reportado_por: "Equipo Diseno",
    asignado_a: "Carlos Ruiz",
    equipo: "Soporte N1",
    origen: "Web",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-20T12:00:00",
    fecha_actualizacion: "2026-05-20T12:30:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-23T12:00:00"
  },
  {
    id: 38,
    codigo: "INC-2026-000038",
    jira_id: null,
    titulo: "Error en el calculo de horas extra en nominas",
    descripcion: "El modulo de nominas calcula mal las horas extra de empleados con jornada partida.",
    estado: "En progreso",
    prioridad: "Critica",
    categoria: "Software",
    reportado_por: "Responsable RRHH",
    asignado_a: "Ana Martinez",
    equipo: "Soporte N2",
    origen: "Email",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-21T08:00:00",
    fecha_actualizacion: "2026-05-21T10:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-21T12:00:00"
  },
  {
    id: 39,
    codigo: "INC-2026-000039",
    jira_id: "GFT-39",
    titulo: "No aparece la opcion de firma en el cliente de correo",
    descripcion: "Varios usuarios de Outlook no tienen visible la opcion de insertar firma en correos nuevos.",
    estado: "Resuelta",
    prioridad: "Baja",
    categoria: "Software",
    reportado_por: "Varios usuarios",
    asignado_a: "Carlos Ruiz",
    equipo: "Soporte N1",
    origen: "Email",
    causa: "La politica de grupo que despliega las firmas tenia un error de ruta",
    solucion: "Se corrigio la ruta en la GPO y se forzó la actualizacion de politicas",
    fecha_creacion: "2026-05-21T09:00:00",
    fecha_actualizacion: "2026-05-21T10:30:00",
    fecha_cierre: "2026-05-21T10:30:00",
    sla_vencimiento: "2026-05-24T09:00:00"
  },
  {
    id: 40,
    codigo: "INC-2026-000040",
    jira_id: null,
    titulo: "La red inalambrica de la planta 2 cae cada hora",
    descripcion: "El punto de acceso de la planta 2 se reinicia solo aproximadamente cada 60 minutos.",
    estado: "En progreso",
    prioridad: "Alta",
    categoria: "Red",
    reportado_por: "Planta 2",
    asignado_a: "Sofia Herrera",
    equipo: "Infraestructura",
    origen: "Telefono",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-21T11:00:00",
    fecha_actualizacion: "2026-05-21T14:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-22T11:00:00"
  },
  {
    id: 41,
    codigo: "INC-2026-000041",
    jira_id: "GFT-41",
    titulo: "Duplicacion de registros en el CRM",
    descripcion: "Al importar clientes desde Excel, el CRM duplica cada registro exactamente dos veces.",
    estado: "Pendiente",
    prioridad: "Media",
    categoria: "Software",
    reportado_por: "Equipo Comercial",
    asignado_a: "Ana Martinez",
    equipo: "Soporte N2",
    origen: "Web",
    causa: "El proceso de importacion tiene un bug conocido con ficheros que tienen BOM en UTF-8",
    solucion: null,
    fecha_creacion: "2026-05-21T15:00:00",
    fecha_actualizacion: "2026-05-22T09:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-23T15:00:00"
  },
  {
    id: 42,
    codigo: "INC-2026-000042",
    jira_id: null,
    titulo: "Correos internos marcados como spam",
    descripcion: "Los correos enviados desde el dominio empresa.com acaban en la carpeta de spam de los destinatarios.",
    estado: "En progreso",
    prioridad: "Alta",
    categoria: "Red",
    reportado_por: "Admin Sistema",
    asignado_a: "Sofia Herrera",
    equipo: "Infraestructura",
    origen: "Email",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-22T08:00:00",
    fecha_actualizacion: "2026-05-22T10:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-23T08:00:00"
  },
  {
    id: 43,
    codigo: "INC-2026-000043",
    jira_id: "GFT-43",
    titulo: "Solicitud de licencia adicional para herramienta de diseno",
    descripcion: "El departamento de marketing necesita una licencia mas de Figma para el nuevo empleado.",
    estado: "Nueva",
    prioridad: "Baja",
    categoria: "Software",
    reportado_por: "Departamento Marketing",
    asignado_a: null,
    equipo: null,
    origen: "Web",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-22T09:00:00",
    fecha_actualizacion: "2026-05-22T09:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-25T09:00:00"
  },
  {
    id: 44,
    codigo: "INC-2026-000044",
    jira_id: null,
    titulo: "El proyector de la sala de formacion no reconoce el HDMI",
    descripcion: "El proyector Epson de la sala de formacion no muestra imagen cuando se conecta por HDMI.",
    estado: "Resuelta",
    prioridad: "Media",
    categoria: "Hardware",
    reportado_por: "Departamento Formacion",
    asignado_a: "Jorge Perez",
    equipo: "Soporte N1",
    origen: "Telefono",
    causa: "El adaptador USB-C a HDMI del portatil era incompatible con el proyector",
    solucion: "Se proporciono un cable HDMI directo y funciono correctamente",
    fecha_creacion: "2026-05-22T10:00:00",
    fecha_actualizacion: "2026-05-22T10:30:00",
    fecha_cierre: "2026-05-22T10:30:00",
    sla_vencimiento: "2026-05-24T10:00:00"
  },
  {
    id: 45,
    codigo: "INC-2026-000045",
    jira_id: "GFT-45",
    titulo: "Los logs del servidor no se estan generando",
    descripcion: "El directorio de logs del servidor de aplicaciones lleva 3 dias sin nuevas entradas.",
    estado: "En progreso",
    prioridad: "Alta",
    categoria: "Software",
    reportado_por: "Admin Sistema",
    asignado_a: "Sofia Herrera",
    equipo: "Infraestructura",
    origen: "Web",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-22T11:00:00",
    fecha_actualizacion: "2026-05-22T13:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-23T11:00:00"
  },
  {
    id: 46,
    codigo: "INC-2026-000046",
    jira_id: null,
    titulo: "No se pueden crear nuevos usuarios en el directorio activo",
    descripcion: "Al intentar crear un usuario en AD, aparece el error 'Insufficient access rights'.",
    estado: "Resuelta",
    prioridad: "Alta",
    categoria: "Accesos",
    reportado_por: "Admin Sistema",
    asignado_a: "Carlos Ruiz",
    equipo: "Soporte N2",
    origen: "Email",
    causa: "La cuenta de servicio de administracion habia perdido permisos tras una actualizacion de politicas",
    solucion: "Se restauraron los permisos de la cuenta de servicio en el controlador de dominio",
    fecha_creacion: "2026-05-23T08:00:00",
    fecha_actualizacion: "2026-05-23T09:30:00",
    fecha_cierre: "2026-05-23T09:30:00",
    sla_vencimiento: "2026-05-24T08:00:00"
  },
  {
    id: 47,
    codigo: "INC-2026-000047",
    jira_id: "GFT-47",
    titulo: "Alertas de seguridad en el firewall corporativo",
    descripcion: "El firewall ha generado 200 alertas de acceso no autorizado desde una IP externa en la ultima hora.",
    estado: "En progreso",
    prioridad: "Critica",
    categoria: "Red",
    reportado_por: "Sistema de Monitoreo",
    asignado_a: "Sofia Herrera",
    equipo: "Infraestructura",
    origen: "Web",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-23T10:00:00",
    fecha_actualizacion: "2026-05-23T10:15:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-23T14:00:00"
  },
  {
    id: 48,
    codigo: "INC-2026-000048",
    jira_id: null,
    titulo: "La aplicacion de tickets no muestra adjuntos",
    descripcion: "Los archivos adjuntos en los tickets no se pueden visualizar ni descargar desde la semana pasada.",
    estado: "Nueva",
    prioridad: "Media",
    categoria: "Software",
    reportado_por: "Equipo Soporte",
    asignado_a: null,
    equipo: null,
    origen: "Web",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-24T09:00:00",
    fecha_actualizacion: "2026-05-24T09:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-26T09:00:00"
  },
  {
    id: 49,
    codigo: "INC-2026-000049",
    jira_id: "GFT-49",
    titulo: "Fallo en la autenticacion de doble factor",
    descripcion: "El sistema de 2FA no envia el codigo SMS a los usuarios con numero de telefono extranjero.",
    estado: "En progreso",
    prioridad: "Alta",
    categoria: "Accesos",
    reportado_por: "Responsable Seguridad",
    asignado_a: "Carlos Ruiz",
    equipo: "Soporte N2",
    origen: "Email",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-24T10:00:00",
    fecha_actualizacion: "2026-05-24T12:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-25T10:00:00"
  },
  {
    id: 50,
    codigo: "INC-2026-000050",
    jira_id: null,
    titulo: "Disco duro casi lleno en el servidor de archivos",
    descripcion: "El servidor de archivos tiene ocupado el 95% del disco. Queda menos de 50GB libres.",
    estado: "Nueva",
    prioridad: "Alta",
    categoria: "Hardware",
    reportado_por: "Admin Sistema",
    asignado_a: null,
    equipo: null,
    origen: "Email",
    causa: null,
    solucion: null,
    fecha_creacion: "2026-05-25T08:00:00",
    fecha_actualizacion: "2026-05-25T08:00:00",
    fecha_cierre: null,
    sla_vencimiento: "2026-05-26T08:00:00"
  }
];

// Exportamos la lista para usarla en los controllers
module.exports = incidencias;